services:
  mongo:
    image: mongo:4.4
    container_name: movie_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: moviereview
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: movie_backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: movie_frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - appnet

volumes:
  mongodb_data:

networks:
  appnet:
    driver: bridge
